### ISSUE TITLE
Change area DSL

### ISSUE THREAD

**Issue by Declow** [Declow/MDSD-sample#5]
It should only be possible to implement one area

**Comment by stehadk** [comment]
NOTE: In order to only include ONE area, I have changed the DSL to the following:

`Production:
	'production' name=ID area=Area terminatables+=TerminatableDef* tasks+=Task+ robots+=Robot+
;`

This ensures ONE area, 0-many TerminatableDef, at least one task and at least one robot, in that particular order.

**Comment by stehadk** [comment]
NOTE: This removes the ProductionItem rule
